config/routes.rb
Rails.application.routes.draw do
  resources :clearance_tasks, :only => [:new, :create]

  root :to => "clearance_tasks#new"
end

app/models/clearance_task.rb
class ClearanceTask
  attr_reader :items
  def initialize(parser, clearance_file)
    @items = parser.new(clearance_file).items
  end

  def perform
    @items.each do |item|
      item.clearance!
    end
  end
end

app/models/concerns/clearance.rb
module Clearance
  extend ActiveSupport::Concern

  included  do
    CLEARANCE_PRICE_DROP = 0.75
    delegate :wholesale_price, :type, to: :style
  end

  def clearance!
    return false unless clearable
    sell_as_clearanced!
    mark_as_clearanced!
  end

  private

  def clearance_price
    clearance_price =
    case type
    when "Dress", "Pants"
      flat_clearance_price < 5 ? 5 : flat_clearance_price
    else
      flat_clearance_price < 2 ? 2 : flat_clearance_price
    end
    clearance_price > wholesale_price ? wholesale_price : clearance_price
  end

  def flat_clearance_price
    0.75 * wholesale_price
  end

  def sell_as_clearanced!
    update_attributes(price_sold: clearance_price, sold_at: DateTime.now)
  end

  def mark_as_clearanced!
    update_attributes(:status => :clearanced)
  end

  def clearable
    status != :sold
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include Clearance
  belongs_to :style

end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_task_controller.rb
class ClearanceTaskController < ApplicationController
  def new
  end

  def create
    @clearance_task = ClearanceTask.new(ClearanceFileParser, permitted_params[:clearance_file])
    render nothing: true, status: :created
  end

  private
  def permitted_params
    params.permit(:clearance_file)
  end
end

app/controllers/clearance_tasks_controller.rb
class ClearanceTasksController < ApplicationController
  def new
  end

  def create
    clearance_file = permitted_params[:clearance_file]
    if clearance_file
      clearance_task = ClearanceTask.new(ClearanceFileParser, clearance_file)
      clearance_task.perform
      @items = clearance_task.items
       render :report
    else
      flash[:error] = "Please upload a file"
      render :new
    end
  end

  private
  def permitted_params
    params.permit(:clearance_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_tasks/new.html.erb
<div class="new-clearance-container">
  <h1 class="title">New Clearance</h1>
  <%= form_tag clearance_tasks_path, method: :post, multipart: true, role: "form", class: "container" do  %>
  <div class="form-group row">
  <div class="error has-error">
      <%= flash[:error]  %>
    </div>
    <%= label_tag :clearance_file, "Upload file for clearance:"  %>
    <%= file_field_tag :clearance_file  %>
  </div>
  <button type="submit" class="btn btn-success btn-submit">Submit</button>
  <% end %>
</div>

app/views/clearance_tasks/report.html.erb
<div class="clearance-report-container">
<h2 class="title">Details of valid items sold under clearance</h2>
  <table class="table">
    <thead>
      <th>Item Id</th>
      <th>Type</th>
      <th>Wholesale price</th>
      <th>Price sold</th>
      <th>Status</th>
    </thead>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id  %></td>
      <td><%= item.type  %></td>
      <td><%= item.wholesale_price  %></td>
      <td><%= item.price_sold  %></td>
      <td><%= item.status  %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>